server:
  port: 9090
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://192.168.10.11:8761/eureka
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: e-bank
          uri: lb://E-BANK
          predicates:
            - Path=/**
        - id: e-health
          uri: lb://E-COVID_HEALTH
          predicates:
            - Path=/**
        - id: e-eductaion
          uri: lb://EDUCATIONDEPARTMENT
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true





